services:
  - type: web
    name: skymessage-server
    env: node
    plan: free
    rootDir: server
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20

  - type: web
    name: skymessage-client
    env: node
    plan: free
    rootDir: client
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s build"
    envVars:
      - key: NODE_VERSION
        value: 20
